//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rota.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public System.DateTime AnalyseStartDate { get; set; }
        public System.DateTime DevelopmentStartDate { get; set; }
        public System.DateTime TestStartDate { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
